First = float(input("กรอกคะเเนนของวิชา Foundation English : "))
Second = float(input("กรอกคะเเนนของวิชา General Business : "))
Third = float(input("กรอกคะเเนนของวิชา Introduction to Computer Systems : "))
Fouth = float(input("กรอกคะเเนนของวิชา Computer Programming : "))
print("--- Your Score ---")
print("Foundation English :",First)
print("General Business :",Second)
print("Introduction to Computer Systems :",Third)
print("Computer Programming :",Fouth)